#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.0.{build}
environment:
  PowerShellGalleryApiKey:
    secure: 3fXfDuds8yhTa7WTOLIEhytrpsej9kcP+4rPrgLaFVmIhimmc+FgUVxkR4u468LH
  GitHubPushFromPlagueHO:
    secure: b/CtRX2iDdREmV5mOgoqK9g6HObrPhjNkjeTxrYMgJbiYYmzvivV1Xp52M79NxDN

build_script:
  - ps: . .\build.ps1 -TaskList Deploy
