#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.0.{build}

image:
- Visual Studio 2017
- Visual Studio 2015

build: false

test_script:
  - ps: . .\psake.ps1 -TaskList Test
